name: fap_group5
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets section
  assets:
    - assets/images/
    - assets/audio/
    - assets/images/instruments/
    - assets/audio/instruments/
    - assets/audio/instruments/guitar_spelling.mp3
  # Add fonts section
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: BikePark
      fonts:
        - asset: assets/fonts/bike-park.otf
